//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogEntry_2026
    {
        public BlogEntry_2026()
        {
            this.Comment_2026 = new HashSet<Comment_2026>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public System.DateTime PostedDate { get; set; }
    
        public virtual ICollection<Comment_2026> Comment_2026 { get; set; }
    }
}
