//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusPoints_2026
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string GroupID { get; set; }
        public byte Point { get; set; }
        public bool HalfPoint { get; set; }
    
        public virtual User_2026 User_2026 { get; set; }
    }
}
