//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public string PostedBy { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string Text { get; set; }
        public Nullable<int> BlogEntryID { get; set; }
    
        public virtual BlogEntry BlogEntry_2022 { get; set; }
    }
}
