//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match_2026
    {
        public Match_2026()
        {
            this.UserMatch_2026 = new HashSet<UserMatch_2026>();
        }
    
        public int ID { get; set; }
        public int HomeTeamID { get; set; }
        public int AwayTeamID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<byte> HomeGoals { get; set; }
        public Nullable<byte> AwayGoals { get; set; }
        public string ResultMark { get; set; }
        public Nullable<double> HomeWinPercent { get; set; }
        public Nullable<double> DrawPercent { get; set; }
        public Nullable<double> AwayWinPercent { get; set; }
    
        public virtual Team_2026 Team_2026 { get; set; }
        public virtual Team_2026 Team_20261 { get; set; }
        public virtual ICollection<UserMatch_2026> UserMatch_2026 { get; set; }
    }
}
