//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public Match()
        {
            this.UserMatch = new HashSet<UserMatch>();
        }
    
        public int ID { get; set; }
        public int HomeTeamID { get; set; }
        public int AwayTeamID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<byte> HomeGoals { get; set; }
        public Nullable<byte> AwayGoals { get; set; }
        public string ResultMark { get; set; }
        public Nullable<double> HomeWinPercent { get; set; }
        public Nullable<double> DrawPercent { get; set; }
        public Nullable<double> AwayWinPercent { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual ICollection<UserMatch> UserMatch { get; set; }
    }
}
