//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamStats
    {
        public int TeamID { get; set; }
        public Nullable<double> PlayoffPercent { get; set; }
        public Nullable<double> QuarterFinalPercent { get; set; }
        public Nullable<double> SemiFinalPercent { get; set; }
        public Nullable<double> FinalPercent { get; set; }
        public Nullable<double> BronzePercent { get; set; }
        public Nullable<double> SilverPercent { get; set; }
        public Nullable<double> GoldPercent { get; set; }
        public Nullable<byte> ScoredGoals { get; set; }
        public Nullable<byte> ConcededGoals { get; set; }
    
        public virtual Team Team_2026 { get; set; }
    }
}
