//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team_2026
    {
        public Team_2026()
        {
            this.Match_2026 = new HashSet<Match_2026>();
            this.Match_20261 = new HashSet<Match_2026>();
            this.UserBronzeTeam_2026 = new HashSet<UserBronzeTeam_2026>();
            this.UserFinalTeams_2026 = new HashSet<UserFinalTeams_2026>();
            this.UserGoldTeam_2026 = new HashSet<UserGoldTeam_2026>();
            this.UserPlayoffTeams_2026 = new HashSet<UserPlayoffTeams_2026>();
            this.UserQFTeams_2026 = new HashSet<UserQFTeams_2026>();
            this.UserSFTeams_2026 = new HashSet<UserSFTeams_2026>();
            this.UserSilverTeam_2026 = new HashSet<UserSilverTeam_2026>();
            this.TopScorer_2026 = new HashSet<TopScorer_2026>();
        }
    
        public int ID { get; set; }
        public string GroupID { get; set; }
        public string TeamName { get; set; }
        public bool IsInPlayOffs { get; set; }
        public bool IsInQuarterFinals { get; set; }
        public bool IsInSemiFinals { get; set; }
        public bool IsInFinal { get; set; }
        public bool WonGold { get; set; }
        public bool WonSilver { get; set; }
        public bool WonBronze { get; set; }
        public Nullable<byte> PlayOffPos { get; set; }
    
        public virtual ICollection<Match_2026> Match_2026 { get; set; }
        public virtual ICollection<Match_2026> Match_20261 { get; set; }
        public virtual ICollection<UserBronzeTeam_2026> UserBronzeTeam_2026 { get; set; }
        public virtual ICollection<UserFinalTeams_2026> UserFinalTeams_2026 { get; set; }
        public virtual ICollection<UserGoldTeam_2026> UserGoldTeam_2026 { get; set; }
        public virtual ICollection<UserPlayoffTeams_2026> UserPlayoffTeams_2026 { get; set; }
        public virtual ICollection<UserQFTeams_2026> UserQFTeams_2026 { get; set; }
        public virtual ICollection<UserSFTeams_2026> UserSFTeams_2026 { get; set; }
        public virtual ICollection<UserSilverTeam_2026> UserSilverTeam_2026 { get; set; }
        public virtual ICollection<TopScorer_2026> TopScorer_2026 { get; set; }
    }
}
