//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tips.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tips_Entities : DbContext
    {
        public Tips_Entities()
            : base("name=Tips_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User_2010> User_2010 { get; set; }
        public DbSet<User_2012> User_2012 { get; set; }
        public DbSet<User_2014> User_2014 { get; set; }
        public DbSet<User_2016> User_2016 { get; set; }
        public DbSet<Standings_2010> Standings_2010 { get; set; }
        public DbSet<Standings_2012> Standings_2012 { get; set; }
        public DbSet<Standings_2014> Standings_2014 { get; set; }
        public DbSet<Standings_2016> Standings_2016 { get; set; }
        public DbSet<Standings_2018> Standings_2018 { get; set; }
        public DbSet<Standings_2021> Standings_2021 { get; set; }
        public DbSet<User_2018> User_2018 { get; set; }
        public DbSet<User_2021> User_2021 { get; set; }
        public DbSet<BlogEntry_2026> BlogEntry_2026 { get; set; }
        public DbSet<BonusPoints_2026> BonusPoints_2026 { get; set; }
        public DbSet<Comment_2026> Comment_2026 { get; set; }
        public DbSet<Match_2026> Match_2026 { get; set; }
        public DbSet<Standings_2024> Standings_2024 { get; set; }
        public DbSet<Standings_2026> Standings_2026 { get; set; }
        public DbSet<Team_2026> Team_2026 { get; set; }
        public DbSet<TopScorer_2026> TopScorer_2026 { get; set; }
        public DbSet<User_2024> User_2024 { get; set; }
        public DbSet<User_2026> User_2026 { get; set; }
        public DbSet<UserBronzeTeam_2026> UserBronzeTeam_2026 { get; set; }
        public DbSet<UserFinalTeams_2026> UserFinalTeams_2026 { get; set; }
        public DbSet<UserGoldTeam_2026> UserGoldTeam_2026 { get; set; }
        public DbSet<UserMatch_2026> UserMatch_2026 { get; set; }
        public DbSet<UserPlayoffTeams_2026> UserPlayoffTeams_2026 { get; set; }
        public DbSet<UserQFTeams_2026> UserQFTeams_2026 { get; set; }
        public DbSet<UserSFTeams_2026> UserSFTeams_2026 { get; set; }
        public DbSet<UserSilverTeam_2026> UserSilverTeam_2026 { get; set; }
    }
}
