//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopScorer_2026
    {
        public TopScorer_2026()
        {
            this.User_2026 = new HashSet<User_2026>();
        }
    
        public int ID { get; set; }
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<bool> IsWinner { get; set; }
        public Nullable<double> WinPercent { get; set; }
    
        public virtual Team_2026 Team_2026 { get; set; }
        public virtual ICollection<User_2026> User_2026 { get; set; }
    }
}
