//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFinalTeams_2026
    {
        public int UserID { get; set; }
        public int TeamID { get; set; }
        public Nullable<byte> Points { get; set; }
    
        public virtual Team_2026 Team_2026 { get; set; }
        public virtual User_2026 User_2026 { get; set; }
    }
}
