//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_2026
    {
        public User_2026()
        {
            this.BonusPoints_2026 = new HashSet<BonusPoints_2026>();
            this.Standings_2026 = new HashSet<Standings_2026>();
            this.UserBronzeTeam_2026 = new HashSet<UserBronzeTeam_2026>();
            this.UserFinalTeams_2026 = new HashSet<UserFinalTeams_2026>();
            this.UserGoldTeam_2026 = new HashSet<UserGoldTeam_2026>();
            this.UserMatch_2026 = new HashSet<UserMatch_2026>();
            this.UserPlayoffTeams_2026 = new HashSet<UserPlayoffTeams_2026>();
            this.UserQFTeams_2026 = new HashSet<UserQFTeams_2026>();
            this.UserSFTeams_2026 = new HashSet<UserSFTeams_2026>();
            this.UserSilverTeam_2026 = new HashSet<UserSilverTeam_2026>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string EmailAddress { get; set; }
        public bool HasPaid { get; set; }
        public System.DateTime PostedDate { get; set; }
        public bool IsConfirmed { get; set; }
        public System.Guid Guid { get; set; }
        public string PayCode { get; set; }
        public Nullable<int> TopScorerID { get; set; }
        public bool IsWinner { get; set; }
    
        public virtual ICollection<BonusPoints_2026> BonusPoints_2026 { get; set; }
        public virtual ICollection<Standings_2026> Standings_2026 { get; set; }
        public virtual TopScorer_2026 TopScorer_2026 { get; set; }
        public virtual ICollection<UserBronzeTeam_2026> UserBronzeTeam_2026 { get; set; }
        public virtual ICollection<UserFinalTeams_2026> UserFinalTeams_2026 { get; set; }
        public virtual ICollection<UserGoldTeam_2026> UserGoldTeam_2026 { get; set; }
        public virtual ICollection<UserMatch_2026> UserMatch_2026 { get; set; }
        public virtual ICollection<UserPlayoffTeams_2026> UserPlayoffTeams_2026 { get; set; }
        public virtual ICollection<UserQFTeams_2026> UserQFTeams_2026 { get; set; }
        public virtual ICollection<UserSFTeams_2026> UserSFTeams_2026 { get; set; }
        public virtual ICollection<UserSilverTeam_2026> UserSilverTeam_2026 { get; set; }
    }
}
