//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BonusPoints = new HashSet<BonusPoints>();
            this.Standings = new HashSet<Standing>();
            this.UserBronzeTeam = new HashSet<UserBronzeTeam>();
            this.UserFinalTeams = new HashSet<UserFinalTeam>();
            this.UserGoldTeam = new HashSet<UserGoldTeam>();
            this.UserMatch = new HashSet<UserMatch>();
            this.UserPlayoffTeams = new HashSet<UserPlayoffTeam>();
            this.UserQFTeams = new HashSet<UserQFTeam>();
            this.UserSFTeams = new HashSet<UserSFTeam>();
            this.UserSilverTeam = new HashSet<UserSilverTeam>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string EmailAddress { get; set; }
        public bool HasPaid { get; set; }
        public System.DateTime PostedDate { get; set; }
        public bool IsConfirmed { get; set; }
        public System.Guid Guid { get; set; }
        public string PayCode { get; set; }
        public Nullable<int> TopScorerID { get; set; }
        public bool IsWinner { get; set; }
    
        public virtual ICollection<BonusPoints> BonusPoints { get; set; }
        public virtual ICollection<Standing> Standings { get; set; }
        public virtual TopScorer TopScorer { get; set; }
        public virtual ICollection<UserBronzeTeam> UserBronzeTeam { get; set; }
        public virtual ICollection<UserFinalTeam> UserFinalTeams { get; set; }
        public virtual ICollection<UserGoldTeam> UserGoldTeam { get; set; }
        public virtual ICollection<UserMatch> UserMatch { get; set; }
        public virtual ICollection<UserPlayoffTeam> UserPlayoffTeams { get; set; }
        public virtual ICollection<UserQFTeam> UserQFTeams { get; set; }
        public virtual ICollection<UserSFTeam> UserSFTeams { get; set; }
        public virtual ICollection<UserSilverTeam> UserSilverTeam { get; set; }
    }
}
