//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMTips_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_2014
    {
        public User_2014()
        {
            this.Standings_2014 = new HashSet<Standings_2014>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string EmailAddress { get; set; }
        public bool HasPaid { get; set; }
        public System.DateTime PostedDate { get; set; }
        public bool IsConfirmed { get; set; }
        public System.Guid Guid { get; set; }
        public string PayCode { get; set; }
        public Nullable<int> TopScorerID { get; set; }
        public bool IsWinner { get; set; }
    
        public virtual ICollection<Standings_2014> Standings_2014 { get; set; }
    }
}
